import type { FunctionalGroup, Reaction } from '@/types'

export const seedGroups: Record<string, FunctionalGroup> = {
  'alkene': {
    id: 'alkene',
    name: 'Alkene',
    formula: 'R-CH=CH₂',
    color: '#4ade80',
    createdAt: 1,
  },
  'alcohol': {
    id: 'alcohol',
    name: 'Alcohol',
    formula: 'R-OH',
    color: '#60a5fa',
    createdAt: 2,
  },
  'aldehyde': {
    id: 'aldehyde',
    name: 'Aldehyde',
    formula: 'R-CHO',
    color: '#f59e0b',
    createdAt: 3,
  },
  'carboxylic-acid': {
    id: 'carboxylic-acid',
    name: 'Carboxylic Acid',
    formula: 'R-COOH',
    color: '#f87171',
    createdAt: 4,
  },
  'alkyl-halide': {
    id: 'alkyl-halide',
    name: 'Alkyl Halide',
    formula: 'R-X',
    color: '#c084fc',
    createdAt: 5,
  },
  'ester': {
    id: 'ester',
    name: 'Ester',
    formula: 'R-COOR\'',
    color: '#fb923c',
    createdAt: 6,
  },
}

export const seedReactions: Record<string, Reaction> = {
  'r1': {
    id: 'r1',
    sourceGroupId: 'alkene',
    targetGroupId: 'alcohol',
    name: 'Hydration (Markovnikov)',
    conditions: 'H₂O, H₂SO₄ (cat.), heat',
    mechanism: [
      { id: 'r1s1', order: 1, description: 'Protonation of the double bond by H⁺ to give the more stable (Markovnikov) carbocation', reagent: 'H⁺', curlyArrowNote: 'π electrons attack H⁺' },
      { id: 'r1s2', order: 2, description: 'Nucleophilic attack of water on the carbocation', reagent: 'H₂O', curlyArrowNote: 'Lone pair of O attacks carbocation' },
      { id: 'r1s3', order: 3, description: 'Deprotonation to give the alcohol product', reagent: '', curlyArrowNote: 'H⁺ lost to regenerate acid catalyst' },
    ],
    hasMechanism: true,
    createdAt: 10,
  },
  'r2': {
    id: 'r2',
    sourceGroupId: 'alkene',
    targetGroupId: 'alkyl-halide',
    name: 'Hydrohalogenation',
    conditions: 'HBr or HCl, no peroxides',
    mechanism: [
      { id: 'r2s1', order: 1, description: 'Protonation of the double bond to form Markovnikov carbocation', reagent: 'HBr', curlyArrowNote: 'π bond attacks H of HBr' },
      { id: 'r2s2', order: 2, description: 'Halide ion attacks the carbocation', reagent: 'Br⁻', curlyArrowNote: 'Br⁻ lone pair attacks carbocation' },
    ],
    hasMechanism: true,
    createdAt: 11,
  },
  'r3': {
    id: 'r3',
    sourceGroupId: 'alcohol',
    targetGroupId: 'aldehyde',
    name: 'Oxidation (primary alcohol)',
    conditions: 'PCC, CH₂Cl₂ or Swern oxidation',
    mechanism: [],
    hasMechanism: false,
    createdAt: 12,
  },
  'r4': {
    id: 'r4',
    sourceGroupId: 'aldehyde',
    targetGroupId: 'carboxylic-acid',
    name: 'Oxidation',
    conditions: 'KMnO₄ / H₂O or CrO₃ / H₂SO₄',
    mechanism: [],
    hasMechanism: false,
    createdAt: 13,
  },
  'r5': {
    id: 'r5',
    sourceGroupId: 'alcohol',
    targetGroupId: 'alkyl-halide',
    name: 'Halogenation',
    conditions: 'SOCl₂, pyridine or PBr₃',
    mechanism: [],
    hasMechanism: false,
    createdAt: 14,
  },
  'r6': {
    id: 'r6',
    sourceGroupId: 'carboxylic-acid',
    targetGroupId: 'ester',
    name: 'Fischer Esterification',
    conditions: 'R\'OH, H₂SO₄ (cat.), heat, reflux',
    mechanism: [
      { id: 'r6s1', order: 1, description: 'Protonation of the carbonyl oxygen activates the carbonyl', reagent: 'H⁺', curlyArrowNote: 'Lone pair of O accepts H⁺' },
      { id: 'r6s2', order: 2, description: 'Nucleophilic addition of alcohol oxygen to the activated carbonyl', reagent: 'R\'OH', curlyArrowNote: 'Lone pair of alcohol O attacks carbonyl C' },
      { id: 'r6s3', order: 3, description: 'Proton transfer and loss of water', reagent: '', curlyArrowNote: 'Proton shuffling then OH₂ leaves' },
    ],
    hasMechanism: true,
    createdAt: 15,
  },
  'r7': {
    id: 'r7',
    sourceGroupId: 'alkyl-halide',
    targetGroupId: 'alcohol',
    name: 'SN2 Hydrolysis',
    conditions: 'NaOH (aq), heat',
    mechanism: [
      { id: 'r7s1', order: 1, description: 'OH⁻ attacks carbon bearing the leaving group from the back (180° angle)', reagent: 'OH⁻', curlyArrowNote: 'Lone pair of OH⁻ attacks C, X⁻ leaves simultaneously (Walden inversion)' },
    ],
    hasMechanism: true,
    createdAt: 16,
  },
}
